sudo: required
services: docker
language: bash
env:
    - ARCH=x86      VERSION=v3.4    QEMU_ARCH=i386
    - ARCH=x86_64   VERSION=v3.4    QEMU_ARCH=x86_64
    - ARCH=armhf    VERSION=v3.4    QEMU_ARCH=arm
    - ARCH=x86      VERSION=v3.5    QEMU_ARCH=i386
    - ARCH=x86_64   VERSION=v3.5    QEMU_ARCH=x86_64
    - ARCH=armhf    VERSION=v3.5    QEMU_ARCH=arm
before_script:
    - sudo apt-get -y install qemu-user-static
script:
    - sudo ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -d "lafin/alpine"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push lafin/alpine; fi
